"""
Trading-Technical-Indicators (tti) python library

File name: constants.py
    Library constants defined under the tti.utils package.
"""

# Possible values for the Trading Signal
TRADE_SIGNALS = {'buy': ('buy', -1), 'hold': ('hold', 0), 'sell': ('sell', 1)}

# When `default` Technical Indicators are used as data features in the ML Data
DEFAULT_TI_FEATURES = [{'ti': 'AccumulationDistributionLine', 'kwrags': {}},
                       {'ti': 'AverageTrueRange', 'kwrags': {}},
                       {'ti': 'BollingerBands', 'kwrags': {}},
                       {'ti': 'ChaikinMoneyFlow', 'kwrags': {}},
                       {'ti': 'ChaikinOscillator', 'kwrags': {}},
                       {'ti': 'ChandeMomentumOscillator', 'kwrags': {}},
                       {'ti': 'CommodityChannelIndex', 'kwrags': {}},
                       {'ti': 'DetrendedPriceOscillator', 'kwrags': {}},
                       {'ti': 'DirectionalMovementIndex', 'kwrags': {}},
                       {'ti': 'DoubleExponentialMovingAverage', 'kwrags': {}},
                       {'ti': 'EaseOfMovement', 'kwrags': {}},
                       {'ti': 'Envelopes', 'kwrags': {}},
                       {'ti': 'FibonacciRetracement', 'kwrags': {}},
                       {'ti': 'ForecastOscillator', 'kwrags': {}},
                       {'ti': 'IchimokuCloud', 'kwrags': {}},
                       {'ti': 'IntradayMovementIndex', 'kwrags': {}},
                       {'ti': 'KlingerOscillator', 'kwrags': {}},
                       {'ti': 'LinearRegressionIndicator', 'kwrags': {}},
                       {'ti': 'LinearRegressionSlope', 'kwrags': {}},
                       {'ti': 'MarketFacilitationIndex', 'kwrags': {}},
                       {'ti': 'MassIndex', 'kwrags': {}},
                       {'ti': 'MedianPrice', 'kwrags': {}},
                       {'ti': 'Momentum', 'kwrags': {}},
                       {'ti': 'MovingAverage', 'kwrags': {'ma_type': 'simple'}},
                       {'ti': 'MovingAverage', 'kwrags': {'ma_type': 'exponential'}},
                       {'ti': 'MovingAverage', 'kwrags': {'ma_type': 'time_series'}},
                       {'ti': 'MovingAverage', 'kwrags': {'ma_type': 'triangular'}},
                       {'ti': 'MovingAverage', 'kwrags': {'ma_type': 'variable'}},
                       {'ti': 'MovingAverageConvergenceDivergence', 'kwrags': {}},
                       {'ti': 'NegativeVolumeIndex', 'kwrags': {}},
                       {'ti': 'OnBalanceVolume', 'kwrags': {}},
                       {'ti': 'ParabolicSAR', 'kwrags': {}},
                       {'ti': 'Performance', 'kwrags': {}},
                       {'ti': 'PositiveVolumeIndex', 'kwrags': {}},
                       {'ti': 'PriceAndVolumeTrend', 'kwrags': {}},
                       {'ti': 'PriceChannel', 'kwrags': {}},
                       {'ti': 'PriceOscillator', 'kwrags': {}},
                       {'ti': 'PriceRateOfChange', 'kwrags': {}},
                       {'ti': 'ProjectionBands', 'kwrags': {}},
                       {'ti': 'ProjectionOscillator', 'kwrags': {}},
                       {'ti': 'Qstick', 'kwrags': {}},
                       {'ti': 'RangeIndicator', 'kwrags': {}},
                       {'ti': 'RelativeMomentumIndex', 'kwrags': {}},
                       {'ti': 'RelativeStrengthIndex', 'kwrags': {}},
                       {'ti': 'RelativeVolatilityIndex', 'kwrags': {}},
                       {'ti': 'StandardDeviation', 'kwrags': {}},
                       {'ti': 'StochasticMomentumIndex', 'kwrags': {}},
                       {'ti': 'StochasticOscillator', 'kwrags': {'k_slowing_periods': 1}},
                       {'ti': 'StochasticOscillator', 'kwrags': {'k_slowing_periods': 3}},
                       {'ti': 'SwingIndex', 'kwrags': {}},
                       {'ti': 'TimeSeriesForecast', 'kwrags': {}},
                       {'ti': 'TripleExponentialMovingAverage', 'kwrags': {}},
                       {'ti': 'TypicalPrice', 'kwrags': {}},
                       {'ti': 'UltimateOscillator', 'kwrags': {}},
                       {'ti': 'VerticalHorizontalFilter', 'kwrags': {}},
                       {'ti': 'VolatilityChaikins', 'kwrags': {}},
                       {'ti': 'VolumeOscillator', 'kwrags': {}},
                       {'ti': 'VolumeRateOfChange', 'kwrags': {}},
                       {'ti': 'WeightedClose', 'kwrags': {}},
                       {'ti': 'WildersSmoothing', 'kwrags': {}},
                       {'ti': 'WilliamsAccumulationDistribution', 'kwrags': {}},
                       {'ti': 'WilliamsR', 'kwrags': {}}]
